# <number> = positive number made up from digits 0 to 9
# <time> = <number> <unit>
#        | "never"
# <unit> = "s" (seconds)
#        | "m" (minutes)
#        | "h" (hours)
#        | "d" (days)
# <percent> = <number> "%"
# <xp-per-level> = <number>

# <time> after which the soul can be collected by anyone
soul-free-after: 1h
# <time> after which the soul disappears
soul-fades-after: never

# How the souls behave in PvP. Possible values:
#   normal: no change
#   disabled: souls are not created in PvP, items and XP drops like in vanilla Minecraft
#   free: created souls are immediately free and can be collected by anyone
pvp-behavior: normal

# <percent> of experience points retained by souls
# OR <xp-per-level> to retain by soul. Vanilla behavior is 7 xp-per-level.
# Soul will never retain more xp than the player has collected.
retained-xp: 90%

# Sound played when collecting XP from a soul
sound-soul-collect-xp: entity.experience_orb.pickup
# Sound played when collecting items from a soul
sound-soul-collect-item: item.trident.return
# Sound played when everything in the soul has been collected and the soul disappears
sound-soul-depleted: entity.generic.extinguish_fire
# Sound played by nearby souls to eligible players, to help them better find the soul
sound-soul-calling: block.beacon.ambient
# Volume with which the soul is calling. Values above 1 only affect distance.
volume-soul-calling: 16
# Sound played to dying players that drop a soul
# NOTE FOR 1.13 USERS: This sound exists only since 1.14, suggested replacement is: block.beacon.power_select
sound-soul-dropped: block.bell.resonate

# Text on a button to free the soul (Set to empty to disable this functionality)
text-free-my-soul: "Free my soul"
# Text displayed as a tooltip on button to free player's soul (Set to empty to disable the tooltip)
text-free-my-soul-tooltip: "Allows other players to collect the soul immediately"